In [1]:
import numpy as np

In [2]:
# Вывод версии и конфигурации
print(np.__version__) 
np.show_config()

1.11.0
lapack_mkl_info:
    library_dirs = ['/home/andrey/programming/miniconda3/lib']
    libraries = ['mkl_lapack95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    include_dirs = ['/home/andrey/programming/miniconda3/include']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['/home/andrey/programming/miniconda3/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    include_dirs = ['/home/andrey/programming/miniconda3/include']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
blas_mkl_info:
    library_dirs = ['/home/andrey/programming/miniconda3/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    include_dirs = ['/home/andrey/programming/miniconda3/include']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['

In [3]:
# создаем вектор(одномерный массив) размера 10, заполненный нулями
Z = np.zeros(10) 
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
# -|-|-|-|-|-|-|-|-, заполенный еденицами
Z = np.ones(10)
print(Z)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [5]:
# -|-|-|-|-|-|-|-|-, заполенный 2.5
Z = np.full(10, 2.5)
print(Z)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


In [6]:
# -|-|-|-|-|-|-|-|-, заполенный значеними от 10 до 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# создаем матрицу (двумерный массив) 3x3 со значениями от 0 до 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# находим индексы ненулевых элементов в [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [10]:
# создаем 3x3 единичную матрицу
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
# создаем массив 3x3x3 со случайными значениями
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.3173855   0.82356333  0.32276041]
  [ 0.58304089  0.8412891   0.42630223]
  [ 0.45376988  0.81875051  0.30064081]]

 [[ 0.85875946  0.57315214  0.66658721]
  [ 0.26302323  0.38419403  0.39267654]
  [ 0.38838501  0.41143102  0.40214673]]

 [[ 0.4493948   0.23500375  0.08542492]
  [ 0.41006578  0.04667238  0.93813386]
  [ 0.88538551  0.42696744  0.70149638]]]


In [12]:
# создаем массив 10x10 со случайными значениями, и находим минимум и максимум
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00692071130492 0.994404556753


In [13]:
# создаем случайный вектор размера 30 и находим среднее значение всех элементов
Z = np.random.random(30)
m = Z.mean()
print(m)

0.627239255978


In [15]:
# создаем 5x5 матрицу с 1,2,3,4 по диагонали
Z = np.diag(np.arange(1, 6), k=0)
print(Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [16]:
# создаем 5x5 матрицу с 1,2,3,4 под диагональю
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [17]:
# создаем 8x8 матрицу и заполнить её в шахматном порядке
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
# создаем 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
# дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [21]:
# перемножение матриц 5x3 и 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [23]:
# есть генератор, делаем с его помощью массив
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [24]:
# сортируем вектор
Z = np.random.random(10)
Z.sort()
print(Z)

[ 0.18950723  0.25718875  0.27753853  0.39230826  0.41184317  0.66612769
  0.71281516  0.72133995  0.73494826  0.8539872 ]


In [25]:
# проверяем, одинаковы ли 2 numpy массива
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [26]:
# делаем массив неизменяемым
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [27]:
# имеем массив 10x2 (точки в декартовой системе координат), преобразуем в полярную
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.97136019  0.39611392  1.09507174  0.83925064  0.81985543  1.11843501
  0.77926076  0.91642297  0.53118924  1.12534492]
[ 0.98603962  0.10317254  0.76517962  0.75733956  0.81325914  0.67333496
  0.34064688  0.26331115  0.50073513  1.00380086]


In [28]:
# заменяем максимальный элемент на ноль
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[  2.08056648e-01   7.30624443e-01   8.09903772e-04   6.50718045e-01
   5.44730901e-01   8.13305213e-01   2.88910948e-01   4.30053837e-01
   3.83767454e-01   0.00000000e+00]


In [29]:
# создаем структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.0, 0.0) (0.1111111111111111, 0.0) (0.2222222222222222, 0.0)
  (0.3333333333333333, 0.0) (0.4444444444444444, 0.0)
  (0.5555555555555556, 0.0) (0.6666666666666666, 0.0)
  (0.7777777777777777, 0.0) (0.8888888888888888, 0.0) (1.0, 0.0)]
 [(0.0, 0.1111111111111111) (0.1111111111111111, 0.1111111111111111)
  (0.2222222222222222, 0.1111111111111111)
  (0.3333333333333333, 0.1111111111111111)
  (0.4444444444444444, 0.1111111111111111)
  (0.5555555555555556, 0.1111111111111111)
  (0.6666666666666666, 0.1111111111111111)
  (0.7777777777777777, 0.1111111111111111)
  (0.8888888888888888, 0.1111111111111111) (1.0, 0.1111111111111111)]
 [(0.0, 0.2222222222222222) (0.1111111111111111, 0.2222222222222222)
  (0.2222222222222222, 0.2222222222222222)
  (0.3333333333333333, 0.2222222222222222)
  (0.4444444444444444, 0.2222222222222222)
  (0.5555555555555556, 0.2222222222222222)
  (0.6666666666666666, 0.2222222222222222)
  (0.7777777777777777, 0.2222222222222222)
  (0.8888888888888888, 0.222222222222

In [31]:
# из двух массивов делаем матрицу Коши C (Cij = 1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


In [32]:
# найдем минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


In [33]:
# напечатаем все значения в массиве
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [36]:
# найдем ближайшее к заданному значению число в заданном массиве
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

65


In [39]:
# создаем структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


In [41]:
# дан массив (100,2) координат, найдем расстояние от каждой точки до каждой
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.40963945  0.69265743  0.76575741  0.84058188  0.075013
   0.9196511   0.60498349  0.70337571  0.46019802]
 [ 0.40963945  0.          0.3665211   0.39246956  0.85985719  0.40895036
   0.51004181  0.27018211  0.65981898  0.11456521]
 [ 0.69265743  0.3665211   0.          0.12845601  1.21120665  0.65713323
   0.42219883  0.09685715  1.00455717  0.25919941]
 [ 0.76575741  0.39246956  0.12845601  0.          1.19132552  0.74002849
   0.29755434  0.17008321  0.98146284  0.3075108 ]
 [ 0.84058188  0.85985719  1.21120665  1.19132552  0.          0.91254931
   1.11153361  1.12004079  0.21043923  0.97431448]
 [ 0.075013    0.40895036  0.65713323  0.74002849  0.91254931  0.
   0.91582044  0.5743466   0.76984314  0.44102028]
 [ 0.9196511   0.51004181  0.42219883  0.29755434  1.11153361  0.91582044
   0.          0.42541264  0.90539807  0.48647387]
 [ 0.60498349  0.27018211  0.09685715  0.17008321  1.12004079  0.5743466
   0.42541264  0.          0.91480227  0.1624745 ]
 [ 0.703375

In [42]:
# преобразуем массив из float в int
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

In [43]:
# эквивалент функции enumerate для numpy массивов
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [44]:
# формируем 2D массив с распределением Гаусса
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [45]:
# отнимаем среднее из каждой строки в матрице
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.27666903 -0.16487987 -0.43542002 -0.39990529  0.34963264  0.3103051
   0.10720484  0.38488545 -0.42708566 -0.00140623]
 [ 0.34294454 -0.06591805  0.18334909 -0.45185783 -0.34997285 -0.05834071
   0.32269707  0.06380462 -0.10720933  0.12050343]
 [-0.15446091 -0.49087949  0.08173381  0.18454528 -0.14921471  0.42927157
   0.15386457  0.30810566 -0.35327953 -0.00968625]
 [ 0.03546005  0.32586879  0.43117076 -0.30042244  0.01310722 -0.4578356
  -0.08170039 -0.30046304  0.17673036  0.1580843 ]
 [ 0.23491525 -0.40381969 -0.18727832  0.20485404  0.28646658 -0.03767688
   0.24834055  0.41122218 -0.36943933 -0.38758438]]


In [47]:
# случайно располагаем p элементов в 2D массив
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [48]:
# сортируем матрицу по n-ому столбцу
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[1 4 7]
 [2 1 0]
 [7 5 7]]
[[2 1 0]
 [1 4 7]
 [7 5 7]]


In [49]:
# определяем, есть ли в 2D массиве нулевые столбцы
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [50]:
# имеем массив, добавим 1 к каждому элементу с индексом, заданным в другом массиве (быть осторожным с повторами)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 6.  2.  2.  3.  4.  4.  2.  2.  2.  3.]


In [51]:
# имеем массив (w,h,3) (картинка) dtype=ubyte, посчитаем количество различных цветов
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [52]:
# имеем четырехмерный массив, посчитаем сумму по последним двум осям
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[51 66 37 49]
 [58 39 68 41]
 [48 69 53 57]]


In [54]:
# найдем диагональные элементы произведения матриц
# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

ValueError: shapes (3,4,3,4) and (5,) not aligned: 4 (dim 3) != 5 (dim 0)

In [55]:
# имеем вектор [1, 2, 3, 4, 5], построим новый вектор с тремя нулями между каждым значением
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [56]:
# поменяем 2 строки в матрице
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [57]:
# в наборе из 10 троек, описывающих 10 треугольников (с общими вершинами), 
# найдем множество уникальных отрезков, составляющих все треугольники
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(2, 77) (2, 82) (5, 79) (5, 97) (9, 12) (9, 24) (12, 24) (13, 15) (13, 75)
 (15, 75) (16, 56) (16, 92) (19, 44) (19, 74) (21, 33) (21, 95) (23, 52)
 (23, 68) (32, 60) (32, 77) (33, 95) (44, 74) (45, 60) (45, 70) (52, 68)
 (56, 92) (60, 70) (60, 77) (77, 82) (79, 97)]


In [58]:
# имеем массив C; создадим массив A, что np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [59]:
# посчитаем среднее, используя плавающее окно
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [60]:
# имеем вектор Z, построим матрицу, первая строка которой (Z[0],Z[1],Z[2]), 
# каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [61]:
# инвертируем булево значение, или поменяем знак у числового массива без создания нового
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

NameError: name 'arr' is not defined

In [62]:
# рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, 
# как вычислить расстояние от р до каждой линии i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[  7.82388242e+00   9.78675725e+00   7.75146102e+00   1.56936174e+00
   4.40889797e+00   8.03722000e+00   9.75660688e-03   3.20738189e+00
   4.37377187e+00   1.77116938e-01]


In [63]:
# имеем массив. Напишем функцию, выделяющую часть массива фиксированного размера 
# с центром в данном элементе (дополненное значением fill если необходимо)
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 7 2 6 9 7 0 0 0 1]
 [1 5 3 5 8 3 4 0 4 1]
 [3 5 0 8 4 2 2 2 3 8]
 [4 8 6 8 2 7 1 4 9 3]
 [0 8 7 6 5 2 9 6 9 9]
 [5 8 8 7 8 2 2 7 7 9]
 [5 9 9 7 2 2 5 4 5 8]
 [2 7 4 7 2 5 1 7 9 1]
 [7 1 0 6 7 7 8 4 3 4]
 [0 2 3 1 6 6 3 7 1 1]]
[[0 0 0 0 0]
 [0 7 7 2 6]
 [0 1 5 3 5]
 [0 3 5 0 8]
 [0 4 8 6 8]]


In [65]:
# Посчитать ранг матрицы
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(Z)
print(rank)

[[ 0.87872292  0.72174266  0.57548981  0.24430333  0.92463263  0.9279247
   0.19556997  0.45352686  0.36536825  0.39273595]
 [ 0.46968183  0.83034893  0.3886339   0.14952362  0.18095095  0.27332434
   0.20118023  0.94115642  0.18215608  0.25535582]
 [ 0.46643069  0.65400192  0.55507314  0.98652253  0.60452874  0.53993246
   0.39338128  0.5332968   0.70547791  0.06958111]
 [ 0.24217914  0.82119182  0.09609854  0.06994384  0.58503095  0.65314201
   0.74373641  0.74087173  0.09190849  0.84258521]
 [ 0.9856728   0.65511411  0.23074133  0.82793695  0.1906702   0.05396123
   0.79412846  0.34183983  0.34015932  0.96886822]
 [ 0.04397353  0.02986807  0.85631357  0.74671705  0.9269182   0.05298824
   0.24122788  0.88408051  0.10511686  0.04599639]
 [ 0.78392935  0.02883712  0.64592668  0.01497864  0.32736053  0.56280818
   0.06317718  0.27769204  0.31476359  0.01487949]
 [ 0.50263521  0.2567943   0.84371434  0.55437318  0.43585837  0.34229967
   0.2315055   0.94666268  0.84691756  0.19928784]
 

In [66]:
# Найти наиболее частое значение в массиве
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [67]:
# Извлечем все смежные 3x3 блоки из 10x10 матрицы
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 3]
   [2 1 2]
   [3 0 3]]

  [[0 3 4]
   [1 2 0]
   [0 3 4]]

  [[3 4 4]
   [2 0 3]
   [3 4 1]]

  [[4 4 0]
   [0 3 1]
   [4 1 1]]

  [[4 0 0]
   [3 1 4]
   [1 1 3]]

  [[0 0 1]
   [1 4 2]
   [1 3 2]]

  [[0 1 1]
   [4 2 0]
   [3 2 2]]

  [[1 1 4]
   [2 0 4]
   [2 2 0]]]


 [[[2 1 2]
   [3 0 3]
   [0 0 2]]

  [[1 2 0]
   [0 3 4]
   [0 2 2]]

  [[2 0 3]
   [3 4 1]
   [2 2 1]]

  [[0 3 1]
   [4 1 1]
   [2 1 0]]

  [[3 1 4]
   [1 1 3]
   [1 0 1]]

  [[1 4 2]
   [1 3 2]
   [0 1 1]]

  [[4 2 0]
   [3 2 2]
   [1 1 2]]

  [[2 0 4]
   [2 2 0]
   [1 2 4]]]


 [[[3 0 3]
   [0 0 2]
   [0 3 1]]

  [[0 3 4]
   [0 2 2]
   [3 1 3]]

  [[3 4 1]
   [2 2 1]
   [1 3 0]]

  [[4 1 1]
   [2 1 0]
   [3 0 0]]

  [[1 1 3]
   [1 0 1]
   [0 0 3]]

  [[1 3 2]
   [0 1 1]
   [0 3 1]]

  [[3 2 2]
   [1 1 2]
   [3 1 3]]

  [[2 2 0]
   [1 2 4]
   [1 3 3]]]


 [[[0 0 2]
   [0 3 1]
   [0 1 4]]

  [[0 2 2]
   [3 1 3]
   [1 4 1]]

  [[2 2 1]
   [1 3 0]
   [4 1 0]]

  [[2 1 0]
   [3 0 0]
   [1 0 2]]

  [[1 0 1]
   

In [68]:
# Создаем подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

SyntaxError: invalid syntax (<ipython-input-68-0b297fe9aa78>, line 5)

In [69]:
# Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). 
# Посчитать сумму p произведений матриц (результат имеет размерность (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


In [71]:
# Дан массив 16x16, посчитать сумму по блокам 4x4
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


In [72]:
# игра "жизнь"
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0
  1 1 0 1 0 0 1 0 1 1 1 0 1]
 [1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 0 1 1 0
  1 1 1 1 1 0 0 0 1 1 1 1 0]
 [0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 1 1 0
  0 1 0 1 0 1 0 0 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0
  0 0 1 1 1 1 1 0 1 0 0 1 0]
 [1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0
  1 0 1 0 0 0 1 1 0 0 1 0 0]
 [0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 1
  1 0 0 0 1 0 0 0 1 1 0 0 0]
 [1 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 1
  0 1 1 0 1 1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 1
  0 1 1 0 1 0 1 1 1 0 0 1 1]
 [1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1 1
  0 1 1 1 0 1 0 1 0 1 1 0 1]
 [0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0

In [73]:
# Найти n наибольших значений в массиве
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9996 9997 9999 9995]


In [74]:
# Построить прямое произведение массивов (все комбинации с каждым элементом)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [75]:
# Даны 2 массива A (8x3) и B (2x2). 
# Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 5 6 7]


In [76]:
# Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 2 1]
 [2 0 4]
 [0 1 3]
 [3 1 4]
 [2 3 1]
 [2 0 0]
 [3 3 3]
 [4 4 2]
 [2 4 3]
 [0 3 0]]
[[0 2 1]
 [2 0 4]
 [0 1 3]
 [3 1 4]
 [2 3 1]
 [2 0 0]
 [4 4 2]
 [2 4 3]
 [0 3 0]]


In [77]:
# Преобразовать вектор чисел в матрицу бинарных представлений
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [78]:
# Дан двумерный массив. Найти все различные строки
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [79]:
# Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [2]:
a = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [3]:
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [5]:
su = sum(a)

In [6]:
type(su)

numpy.ndarray

In [7]:
su_2 = 0
for item in a:
    su_2 += item

In [8]:
su_2

array([6, 6, 6])

In [13]:
su_3 = np.sum(a, axis=0)

In [14]:
su_3

array([6, 6, 6])